default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: view_backed
  password: view_backed

development:
  <<: *default
  database: view_backed_development

test:
  <<: *default
  database: view_backed_test
