version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
      - image: circleci/postgres:9.6
        environment:
            POSTGRES_HOST: localhost
            POSTGRES_USER: view_backed
            POSTGRES_DB: view_backed_test
            POSTGRES_PASSWORD: view_backed

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run: bundle exec appraisal install

      - run: bundle exec appraisal 'cd spec/dummy/ && rake db:create'
      - run: bundle exec appraisal 'cd spec/dummy/ && rake db:schema:load'

      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"

            bundle exec appraisal rspec --format progress \
                                        --format RspecJunitFormatter \
                                        --out /tmp/test-results/rspec.xml \
                                        --format progress \
                                        $TEST_FILES

      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
